name: Build and Deploy to Docker Hub

# Trigger the workflow on a push to the specified branch
on:
  push:
    branches:
      - main  # Replace with your desired branch, e.g., "new-branch"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .                              # Build context (root of the repository)
          file: ./docker/Dockerfile.user          # Path to the Dockerfile
          push: true                              # Push to Docker Hub
          tags: |
            mohammadsaif786/week-18:latest        # Replace with your Docker Hub repo and tag

      # Step 4 (Optional): Verify the Pushed Image
      - name: Verify Pushed Image
        run: docker pull mohammadsaif786/week-18:latest
