name: Build and Deploy to Docker Hub

on: 
  push: 
    branches:
      	-new-branch

jobs: 
  build-and-push: 
    runs-on: ubuntu
    steps: 
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2  
      with: 
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: "mohammadsaif786/week-18:latest"

    - name: Verify Pushed Image
      run: docker pull mohammadsaif786/week-18:latest